import type {Metadata}
from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";

const inter = Inter({subsets: ['latin']})

export const metadata : Metadata = {
    title: 'Viralyst',
    description: 'Generated by sayjun'
}

export default function RootLayout({children} : {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <script async src="https://www.googletagmanager.com/gtag/js?id=G-8728V4EJZE"></script>
                <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'G-8728V4EJZE');
                </script>
            </head>
            <body className={inter.className + " " + "overflow-x-hidden"} >
                <Providers>
                  {children}
                </Providers>
            </body>
        </html>
    )
}
